services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgres
    networks:
      - bigquery-dbt-crypto-pipeline
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase_password
    networks:
      - bigquery-dbt-crypto-pipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  bigquery-dbt-crypto-pipeline:
    name: bigquery-dbt-crypto-pipeline
    driver: bridge
    external: true

volumes:
  postgres_data:
