version: 2

sources:
  - name: raw  # Nome do source no dbt
    schema: crypto_pipeline_raw  # Schema no BigQuery onde as tabelas estão armazenadas
    tables:
      - name: raw_binance_klines_BTCBRL
        description: "Dados brutos de Binance para BTC/BRL"
      - name: raw_binance_klines_ETHBRL
        description: "Dados brutos de Binance para ETH/BRL"
      - name: raw_binance_klines_SOLBRL
        description: "Dados brutos de Binance para SOL/BRL"
