gcp:
  project: "bigquery-dbt-crypto-pipeline" 
  bucket_name: "binance-api"
  dataset_id: "raw"
  bigquery_conn_id: "bigquery-con"

binance:
  base_url: "https://api.binance.com/api/v3/klines"
  cryptos: ["BTCBRL", "ETHBRL", "SOLBRL"]
  interval: "1m"
  limit: 1000
  default_start_time: 1577836800000 # 2020-01-01 00:00:00
